FROM python

WORKDIR /app

COPY . /app

CMD ["python","rng.py"]


# Run this in interactive and TTY mode ... docker run -it <container>
# Docker start or docker -d work too
# docker run or docker start -a <container> reattaches