version: '3.8'
services:
    server:
        image: 'nginx:stable-alpine'
        user: '1000:1000'
        ports:
            - '8000:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    php:
        user: '1000:1000'
        build:
            context: ./docker
            dockerfile: php.dockerfile
        volumes:
            - ./src:/var/www/html:delegated
            # Improves performance because it won't write to host machine immediately
    mysql:
        user: '1000:1000'
        image: mysql:5.7
        env_file:
            - ./env/mysql.env

    composer:
        user: '1000:1000'
        build:
            context: ./docker
            dockerfile: composer.dockerfile
        volumes:
            - ./src:/var/www/html

    # artisan:
    # npm:
